---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #username: "{{ username }}"
  
  tasks:
    - name: Print Sender's sfas ID
      debug:
        msg: "Sender's email ID is {{ username }}"



#   tasks:
#     # - name: Generate Password
#     #   community.general.random_password:
#     #     length: 12
#     #     special: yes
#     #     digits: yes
#     #     upperalpha: yes
#     #     loweralpha: yes
#     #   register: generated_password

#     # - name: Display Generated Password for testing purpose
#     #   debug:
#     #     var: generated_password.password
#     - name: Print Sender's Email ID
#       debug:
#         msg: "Sender's Email ID: {{ username }}"
#     # - name: Create IAM Users
#     #   iam_user:
#     #     name: "{{ username }}"
#     #     state: present
#     #     password: 'Welcome@123456'
