---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #username: "{{ username }}"
  
  tasks:
    - name: Print access key
      debug:
        msg: "Profile acces key {{ aws_access_key_id }}"
    - name: Print Secret key
      debug:
        msg: "Profile password {{ aws_secret_access_key }}"
    - name: Create IAM User
      iam_user:
        name: "{{ username }}"
        state: present
        password: "Welcome@123456"
        access_key: "{{ aws_access_key_id }}"
        secret_key: "{{ aws_secret_access_key }}"