pipeline {
    agent any

    parameters {
        string(name: 'USERNAME', defaultValue: '', description: 'Enter the username')
        string(name: 'USER_EMAIL', defaultValue: '', description: 'Enter the user email')
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS')
        AWS_SECRET_ACCESS_KEY = credentials('AWS')
    } 

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'Githubcreds', branch: 'create_users', url: 'https://github.com/devsecopsmurali/ansible-playbook-builds.git'
            }
        }

        stage('Execute Ansible playbook') {
            steps {
                script {
                    ansiblePlaybook(
                        playbook: 'create_user.yml',
                        inventory: 'localhost',
                        extras: "-e 'username=${params.USERNAME}' -e 'useremail=${params.USER_EMAIL}' -e 'aws_access_key_id=${AWS_ACCESS_KEY_ID}' -e 'aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}'"
                    )
                }
            }
            steps {
                script {
                    def username = params.USERNAME
                    // Rest of your steps using the 'username' variable
                }
            }
        }
    }

    post {
        success {
            // Send email on success
            //def username = params.USERNAME
            emailext subject: 'Jenkins Build Successful',
                      body: 'Your build is successful. Congratulations! Username:  ${username}',
                      recipientProviders: [[$class: 'CulpritsRecipientProvider']],
                      to: params.USER_EMAIL
        }
        failure {
            // Send email on failure
            emailext subject: 'Jenkins Build Failed',
                      body: 'Your build has failed. Please check the Jenkins logs for details.',
                      recipientProviders: [[$class: 'CulpritsRecipientProvider']],
                      to: params.USER_EMAIL
        }
    }
}
