pipeline {
    agent any

    parameters {
        string(name: 'USERNAME', defaultValue: '', description: 'Enter the username')
        string(name: 'USER_EMAIL', defaultValue: '', description: 'Enter the user email')
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS')
        AWS_SECRET_ACCESS_KEY = credentials('AWS')
    } 

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'Githubcreds', branch: 'create_users', url: 'https://github.com/devsecopsmurali/ansible-playbook-builds.git'
            }
        }

        stage('Execute Ansible playbook') {
            steps {
                script {
                    ansiblePlaybook(
                        playbook: 'create_user.yml',
                        inventory: 'localhost',
                        extras: "-e 'username=${params.USERNAME}' -e 'useremail=${params.USER_EMAIL}'"
                    )
                }
            }
        }
    }
}
