pipeline {
    agent any

    parameters {
        string(name: 'USERNAME', defaultValue: '', description: 'Enter the username')
        string(name: 'USEREMAIL', defaultValue: '', description: 'Enter the user email')
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS')
        AWS_SECRET_ACCESS_KEY = credentials('AWS')
    } 

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'Githubcreds', branch: 'create_users', url: 'https://github.com/devsecopsmurali/ansible-playbook-builds.git'
            }
        }
        stage('Example Stage') {
            steps {
                script {
                    def username = params.USERNAME
                }
            }
        }
        stage('Execute Ansible playbook') {
            steps {
                script {
                    ansiblePlaybook(
                        playbook: 'create_user.yml',
                        inventory: 'localhost',
                        extras: "-e 'username=${params.USERNAME}' -e 'userEmail=${params.USEREMAIL}' -e 'aws_access_key_id=${AWS_ACCESS_KEY_ID}' -e 'aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}'"
                    )
                }
            }
            
        }
    }

    post {
        success {
        emailext subject: 'IAM User Creation Successful',
                  mimeType: 'text/html',
                  body: '''<html>
                            <body>
                                <h2 style="color: #3498db;">Your IAM User Creation Successful. Congratulations!</h2>
                                <p style="color: #3498db;">
                                <strong style="color: #3498db;">Account ID (12 digits) or account alias: 746982785361</strong>
                                <strong style="color: #3498db;">Your IAM User Name: ${username} </strong>
                                <strong style="color: #3498db;">Your IAM Password: Welcome@123456</strong>
                                <strong style="color: #3498db;">Thank you for using AWS service!</strong>
                                </p>
                            </body>
                          </html>''',
                  recipientProviders: [[$class: 'CulpritsRecipientProvider']],
                  to: params.USEREMAIL
    }
        failure {
            // Send email on failure
            emailext subject: 'Jenkins Build Failed',
                      body: 'Your build has failed. Please check the Jenkins logs for details.',
                      recipientProviders: [[$class: 'CulpritsRecipientProvider']],
                      to: params.USEREMAIL
        }
    }
}
